name: CI Workflow

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-base-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    services:
      docker:
        image: docker:latest
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${GITHUB_REPOSITORY_OWNER}/service_base:latest
          context: service_base
          file: Dockerfile
          pull: true
          network: host
          

  build-ros-image:
    runs-on: ubuntu-latest
    needs: [build-base-image]
    permissions:
      contents: read
      packages: write
    services:
      docker:
        image: docker:latest
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Wait for Docker
        run: |
          until docker info; do sleep 1; done
      # - name: Build and Push ROS Image
      #   run: |
      #     source build_and_push.sh ros2_base ghcr.io/${GITHUB_REPOSITORY_OWNER}/service_base:latest
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${GITHUB_REPOSITORY_OWNER}/ros2_base:latest
          context: ros2_base
          file: Dockerfile
          pull: true
          network: host
          build-args: BASE_IMAGE=ghcr.io/${GITHUB_REPOSITORY_OWNER}/service_base:latest
