name: CI Workflow

on:
  push:
    branches:
      - master
      - develop


jobs:
  build-service-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set tag postfix
        id: set-postfix
        run: |
          tags=""
          if [[ "${{ github.ref_name }}" == "master" ]]; then
            tags="${tags},ghcr.io/${{ github.repository_owner }}/service_base:latest"
            tags="${tags},ghcr.io/${{ github.repository_owner }}/service_base:latest-stable"
          elif [[ "${{ github.ref_name }}" == "develop" ]]; then
            tags="${tags},ghcr.io/${{ github.repository_owner }}/service_base:latest"
          fi
          tags="${tags},ghcr.io/${{ github.repository_owner }}/service_base:${{ github.run_number }}"
          echo "TAGS=${tags}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.TAGS }}
          context: service_base
          pull: true
          network: host
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/service_base:latest
          cache-to: type=inline


  build-ros1-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set tag postfix
        id: set-postfix
        run: |
          tags=""
          if [[ "${{ github.ref_name }}" == "master" ]]; then
            tags="${tags},ghcr.io/${{ github.repository_owner }}/ros1_base:latest"
            tags="${tags},ghcr.io/${{ github.repository_owner }}/ros1_base:latest-stable"
          elif [[ "${{ github.ref_name }}" == "develop" ]]; then
            tags="${tags},ghcr.io/${{ github.repository_owner }}/ros1_base:latest"
          fi
          tags="${tags},ghcr.io/${{ github.repository_owner }}/ros1_base:${{ github.run_number }}"
          echo "TAGS=${tags}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.TAGS }}
          context: ros1_base
          pull: true
          network: host
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ros1_base:latest
          cache-to: type=inline

          
  build-ros2-image:
    runs-on: ubuntu-latest
    needs: [build-service-image]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set tag postfix
        id: set-postfix
        run: |
          tags=""
          if [[ "${{ github.ref_name }}" == "master" ]]; then
            tags="${tags},ghcr.io/${{ github.repository_owner }}/ros2_base:latest"
            tags="${tags},ghcr.io/${{ github.repository_owner }}/ros2_base:latest-stable"
          elif [[ "${{ github.ref_name }}" == "develop" ]]; then
            tags="${tags},ghcr.io/${{ github.repository_owner }}/ros2_base:latest"
          fi
          tags="${tags},ghcr.io/${{ github.repository_owner }}/ros2_base:${{ github.run_number }}"
          echo "TAGS=${tags}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.TAGS }}
          context: ros2_base
          pull: true
          network: host
          build-args: BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/service_base:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ros2_base:latest
          cache-to: type=inline


  build-moveit2-image:
    runs-on: ubuntu-latest
    needs: [build-service-image]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set tag postfix
        id: set-postfix
        run: |
          tags=""
          if [[ "${{ github.ref_name }}" == "master" ]]; then
            tags="${tags},ghcr.io/${{ github.repository_owner }}/moveit2_base:latest"
            tags="${tags},ghcr.io/${{ github.repository_owner }}/moveit2_base:latest-stable"
          elif [[ "${{ github.ref_name }}" == "develop" ]]; then
            tags="${tags},ghcr.io/${{ github.repository_owner }}/moveit2_base:latest"
          fi
          tags="${tags},ghcr.io/${{ github.repository_owner }}/moveit2_base:${{ github.run_number }}"
          echo "TAGS=${tags}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.TAGS }}
          context: moveit2_base
          pull: true
          network: host
          build-args: BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/service_base:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/moveit2_base:latest
          cache-to: type=inline

  build-ocam-image:
    runs-on: ubuntu-latest
    needs: [build-ros1-image]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set tag postfix
        id: set-postfix
        run: |
          tags=""
          if [[ "${{ github.ref_name }}" == "master" ]]; then
            tags="${tags},ghcr.io/${{ github.repository_owner }}/ocam:latest"
            tags="${tags},ghcr.io/${{ github.repository_owner }}/ocam:latest-stable"
          elif [[ "${{ github.ref_name }}" == "develop" ]]; then
            tags="${tags},ghcr.io/${{ github.repository_owner }}/ocam:latest"
          fi
          tags="${tags},ghcr.io/${{ github.repository_owner }}/ocam:${{ github.run_number }}"
          echo "TAGS=${tags}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.TAGS }}
          context: ocam
          pull: true
          network: host
          build-args: BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/ros1_base:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ocam:latest
          cache-to: type=inline
